language: elixir

dist: trusty
sudo: false

services:
  - redis-server

matrix:
  include:
    - elixir: 1.16.0
      otp_release: 26.2.1
    - elixir: 1.7.4
      otp_release: 21.0
    - elixir: 1.7.4
      otp_release: 20.3.1
    - elixir: 1.6.6
      otp_release: 19.3
    - elixir: 1.5.3
      otp_release: 18.3
    - elixir: 1.5.3
      otp_release: 17.5
